variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

image: eur0c.laas.fr:5000/humanoid-path-planner/hpp_foottrajectory

build_job:
  stage: build
  script:
    - cmake .
    - make
  artifacts:
    untracked: true

test_job:
  stage: test
  script:
    - make test
